# Minecraft Rakefile Yaml configruation


# # top level is server nickname (shouldnt have spaces)
sigma:
    minecraft_server_directory: "~/minecraft/"
    backup_directory:           "/data/Games/Minecraft/Server\ Backups/"
    minecraft_version:          "1.7.4"
    render_directory:           "/srv/http/sigma/"

